version: '3'

services:
  golang:
    build:
      context: .
      dockerfile: dockerfile
    image: 192.168.0.31:5000/myhomesv  ## goes to local registry
    ports:
      - 8056:8080
    environment:
      - ENV=development
    # volumes:
    #   - /src:/go/src
      # - type: bind
      #   source: "./src"
      #   target: "/go/src"
      # 開発時は設定ファイルはgolangプロジェクト内に配置してそのまま取り込む
    tty: true
    restart: always